# Generated by Django 5.0.6 on 2024-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('RollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Subject1', models.IntegerField()),
                ('Subject2', models.IntegerField()),
                ('Subject3', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
